#!/bin/bash
FILE_NAME=$1
if [ ! -n "$FILE_NAME" ]; then
    echo -e "Usage: \n\t$0 file_name"
    exit -1
fi
iconv -f cp936 -t utf8 $FILE_NAME -o $FILE_NAME.bak \
	&& mv $FILE_NAME.bak $FILE_NAME \
	&& echo "convert $FILE_NAME to utf8 success"
